using MCK9595.APIMocker.Core.Storage;
using Xunit;

namespace MCK9595.APIMocker.Core.Tests;

public class InMemoryDataStoreTests
{
    private readonly InMemoryDataStore _store = new();

    [Fact]
    public void Create_AddsItemWithAutoGeneratedId()
    {
        var item = new Dictionary<string, object?> { ["name"] = "Test" };

        var created = _store.Create("users", item);

        Assert.Equal(1, created["id"]);
        Assert.Equal("Test", created["name"]);
    }

    [Fact]
    public void GetAll_ReturnsAllItems()
    {
        _store.Create("users", new Dictionary<string, object?> { ["name"] = "User1" });
        _store.Create("users", new Dictionary<string, object?> { ["name"] = "User2" });

        var items = _store.GetAll("users");

        Assert.Equal(2, items.Count);
    }

    [Fact]
    public void GetById_ReturnsCorrectItem()
    {
        _store.Create("users", new Dictionary<string, object?> { ["name"] = "User1" });
        var created = _store.Create("users", new Dictionary<string, object?> { ["name"] = "User2" });

        var item = _store.GetById("users", created["id"]!);

        Assert.NotNull(item);
        Assert.Equal("User2", item["name"]);
    }

    [Fact]
    public void GetById_ReturnsNullForNonExistent()
    {
        var item = _store.GetById("users", 999);

        Assert.Null(item);
    }

    [Fact]
    public void Update_ModifiesExistingItem()
    {
        var created = _store.Create("users", new Dictionary<string, object?> { ["name"] = "Original" });
        var updated = _store.Update("users", created["id"]!, new Dictionary<string, object?> { ["name"] = "Updated" });

        Assert.NotNull(updated);
        Assert.Equal("Updated", updated["name"]);
        Assert.Equal(created["id"], updated["id"]);
    }

    [Fact]
    public void Delete_RemovesItem()
    {
        var created = _store.Create("users", new Dictionary<string, object?> { ["name"] = "ToDelete" });

        var deleted = _store.Delete("users", created["id"]!);
        var item = _store.GetById("users", created["id"]!);

        Assert.True(deleted);
        Assert.Null(item);
    }

    [Fact]
    public void Query_FiltersCorrectly()
    {
        var store = new InMemoryDataStore();
        store.Create("users", new Dictionary<string, object?> { ["name"] = "Alice", ["role"] = "admin" });
        store.Create("users", new Dictionary<string, object?> { ["name"] = "Bob", ["role"] = "user" });
        store.Create("users", new Dictionary<string, object?> { ["name"] = "Charlie", ["role"] = "admin" });

        var result = store.Query("users", new QueryOptions(
            Filters: new Dictionary<string, string> { ["role"] = "admin" }
        ));

        Assert.Equal(2, result.Items.Count);
        Assert.Equal(2, result.TotalCount);
    }

    [Fact]
    public void Query_SortsCorrectly()
    {
        var store = new InMemoryDataStore();
        store.Create("users", new Dictionary<string, object?> { ["name"] = "Charlie" });
        store.Create("users", new Dictionary<string, object?> { ["name"] = "Alice" });
        store.Create("users", new Dictionary<string, object?> { ["name"] = "Bob" });

        var result = store.Query("users", new QueryOptions(SortBy: "name"));

        Assert.Equal("Alice", result.Items[0]["name"]);
        Assert.Equal("Bob", result.Items[1]["name"]);
        Assert.Equal("Charlie", result.Items[2]["name"]);
    }

    [Fact]
    public void Query_PaginatesCorrectly()
    {
        var store = new InMemoryDataStore();
        for (int i = 1; i <= 10; i++)
        {
            store.Create("users", new Dictionary<string, object?> { ["name"] = $"User{i}" });
        }

        var result = store.Query("users", new QueryOptions(Skip: 2, Take: 3));

        Assert.Equal(3, result.Items.Count);
        Assert.Equal(10, result.TotalCount);
        Assert.Equal("User3", result.Items[0]["name"]);
    }
}
